services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - client
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    restart: unless-stopped
    expose:
      - "8080"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    restart: unless-stopped
    expose:
      - "4321"
    depends_on:
      - server

networks:
  default:
    name: okn-network-dev