services:
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - client
  #     - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    restart: unless-stopped
    expose:
      - "8080"
    ports:
      - "8080:8080"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    restart: unless-stopped
    env_file:
      - ./client/.env
    expose:
      - "4321"
    ports:
      - "4321:4321"
    depends_on:
      - server

networks:
  default:
    name: okn-network-dev